### ISSUE TITLE
add support for user provided firewall names

### ISSUE THREAD

**Issue by mk-avx** [terraform-aviatrix-modules/terraform-aviatrix-aws-transit-firenet#42]

**Comment by Dennizz** [comment]
Do you need complete custom naming support, e.g. through a list variable:

variable "fw_names" {
  type = list(string)
  default = [
     "fw1-az1",
     "fw2-az1",
     "fw1-az2",
     "fw2-az2",
  ]
}

Or just be able to set a prefix, and have the module append it with some suffix to make it unique?

**Comment by Dennizz** [comment]
Please test master branch with this new argument:

```
module "transit_firenet_1" {
  source = "git::https://github.com/terraform-aviatrix-modules/terraform-aviatrix-aws-transit-firenet"

  custom_fw_names = [
    "fw1-az1",
    "fw2-az1",
    "fw1-az2",
    "fw2-az2",
  ]
  ...
}
```

**Comment by Dennizz** [comment]
Implemented
